### ISSUE TITLE
Master issue for new API

### ISSUE THREAD

**Issue by dangunter** [watertap-org/watertap-ui#37]
Many changes to the UI's backend API, complicated by requirements of coordinated changes in watertap repo

- [ ] PR https://github.com/watertap-org/watertap-ui/pull/36 is the main new API changes

Before this can pass tests, the following must be merged in the *watertap* repo

- [ ] https://github.com/watertap-org/watertap/pull/682 which modifies semantics of the call to `FlowsheetInterface` constructor
- [ ] https://github.com/watertap-org/watertap/pull/681 which provides a name for the flowsheet (even if the user doesn't give one)
