### ISSUE TITLE
WaterTAP GUI Features

### ISSUE THREAD

**Issue by hunterbarber** [watertap-org/watertap-ui#97]
### Description

Master issue for GUI feature requests that come up as developers work to expand GUI library. These requests aren't required for implementation of new flowsheets, but either ease the development of adding new flowsheets to the UI or are enhanced visualization and interaction tools from the user side.

- [ ] **Stream tables for UI output:** Posed in watertap-org/watertap#1231, remove the need for developers to define each individual state variable for all streams, and instead point to state blocks and variables in which the UI can construct a stream table doing the combination of all state blocks (streams) and desired output variables.
- [x] **User input based `build_options`:** Posed in watertap-org/watertap#1239, currently users may build flowsheets by selecting from predefined options in a developer specified list. For generalizable flowsheets, input based `build_options` as a `str`, `float`, or `int` (able to be validated by `class` instead of within list) may be useful for flowsheet robustness and customization.
- [ ] **LCOW and SEC breakdown functionality and display in UI:** Posed in watertap-org/watertap#1256, Streamline the breakdown of LCOW and SEC calculations in the costing package and quickly displaying them (e.g., stacked bar charts) in the UI.
- [ ] https://github.com/watertap-org/watertap/issues/1293 Extend the export API to allow construction of user-specified graphs for display of results

### Motivation

These feature requests may be prioritized by the GUI team, but are not required for the implementation of new flowsheets. However, these features would to advance the GUI ease of use.

**Comment by MichaelPesce** [comment]
closing this. transferred the individual issues to [idaes-flowsheet-processor-ui issues](https://github.com/prommis/idaes-flowsheet-processor-ui/issues)
